apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m5p5sgiyy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m5p5sgiyy-go 
  name: m5p5sgiyy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m5p5sgiyy-go 
